// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC76JI-cQ9UP0gyGU2bAtYkGcs4Fev-Vyc',
    appId: '1:854232669396:web:760bc6b429ef2d31f8af41',
    messagingSenderId: '854232669396',
    projectId: 'cinema-ticket-booking-d8f2e',
    authDomain: 'cinema-ticket-booking-d8f2e.firebaseapp.com',
    storageBucket: 'cinema-ticket-booking-d8f2e.appspot.com',
    measurementId: 'G-TRNN6J4XR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdiU2lf7UEnzDOSwpppeWrG0MCvsVe6AE',
    appId: '1:854232669396:android:a3554e94aef219def8af41',
    messagingSenderId: '854232669396',
    projectId: 'cinema-ticket-booking-d8f2e',
    storageBucket: 'cinema-ticket-booking-d8f2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy8uVy_IxqfShEXEqsf5mi_ylNtPyMI74',
    appId: '1:854232669396:ios:f2aad2b575e3ec9bf8af41',
    messagingSenderId: '854232669396',
    projectId: 'cinema-ticket-booking-d8f2e',
    storageBucket: 'cinema-ticket-booking-d8f2e.appspot.com',
    iosBundleId: 'com.example.cinemaBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy8uVy_IxqfShEXEqsf5mi_ylNtPyMI74',
    appId: '1:854232669396:ios:f2aad2b575e3ec9bf8af41',
    messagingSenderId: '854232669396',
    projectId: 'cinema-ticket-booking-d8f2e',
    storageBucket: 'cinema-ticket-booking-d8f2e.appspot.com',
    iosBundleId: 'com.example.cinemaBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC76JI-cQ9UP0gyGU2bAtYkGcs4Fev-Vyc',
    appId: '1:854232669396:web:2bb515c0fee07044f8af41',
    messagingSenderId: '854232669396',
    projectId: 'cinema-ticket-booking-d8f2e',
    authDomain: 'cinema-ticket-booking-d8f2e.firebaseapp.com',
    storageBucket: 'cinema-ticket-booking-d8f2e.appspot.com',
    measurementId: 'G-4MKXDC2T1J',
  );
}
